export const SET_MENU_ITEM = 'SET_MENU_ITEM';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';

export const ENVIRONMENT_CHECK_LIST_PATH = '/tool-equipment-checking';
// route path for sampling
export const INSPECTION_LIST_PATH = '/inspection-list';
export const INSPECTION_REPORT_PATH = '/inspection-report';
export const SAMPLING_MATERIAL_GROUP_LIST_PATH = '/material-group-list';
export const SAMPLING_MATERIAL_GROUP_DETAIL_PATH = '/material-group';
export const SAMPLING_SUMMARIZE_STORE_PATH = '/summarize-store';
export const SAMPLING_SUMMARIZE_STORE_DETAIL_PATH = '/summarize-store/detail';
export const SAMPLING_SUMMARIZE_QC_PATH = '/summarize-qc';
export const SAMPLING_SUMMARIZE_QC_DETAIL_PATH = '/summarize-qc/detail';
export const SAMPLING_PROCESS_PATH = '/sampling-process';
export const SAMPLING_PROCESS_GROUP_PATH = `${SAMPLING_PROCESS_PATH}/group`;
export const SAMPLING_PROCESS_STEP_PATH = `${SAMPLING_PROCESS_PATH}/step`;
// route path for dispensing
export const PROCESS_ORDER_PATH = '/process-order';
export const PROCESS_ORDER_CREATE_PATH = `${PROCESS_ORDER_PATH}/create`;
export const PROCESS_ORDER_DETAIL_PATH = `${PROCESS_ORDER_PATH}/detail`;
export const DISPENSING_GROUP_LIST_PATH = '/dispensing-group';
export const DISPENSING_GROUP_DETAIL_PATH = `${DISPENSING_GROUP_LIST_PATH}/detail`;
export const DISPENSING_SUMMARIZE_PATH = '/dispensing-summarize';
export const DISPENSING_SUMMARIZE_DETAIL_PATH = `${DISPENSING_SUMMARIZE_PATH}/detail`;
export const DISPENSING_PROCESS_PATH = '/dispensing-process';
export const DISPENSING_PROCESS_GROUP_PATH = `${DISPENSING_PROCESS_PATH}/group`;
export const DISPENSING_PROCESS_STEP_PATH = `${DISPENSING_PROCESS_PATH}/step`;
export const DISPENSING_ADJUSTMENT_PATH = '/dispensing-adjustment';
// route path for environment checking
export const ENVIRONMENT_CHECKING_PATH = '/tool-equipment-checking';
export const ENVIRONMENT_CHECKING_STEPPER_PATH_N2GAS = `${ENVIRONMENT_CHECKING_PATH}/n2-gas`;
export const ENVIRONMENT_CHECKING_STEPPER_PATH_WEIGHING_SCALE_EFF = `${ENVIRONMENT_CHECKING_PATH}/weighing-scale-efficiency`;
export const ENVIRONMENT_CHECKING_STEPPER_PATH_PRESSURE_DIFF = `${ENVIRONMENT_CHECKING_PATH}/pressure-diff`;
export const ENVIRONMENT_CHECKING_STEPPER_PATH_WEIGHING_BOOTH_EFF = `${ENVIRONMENT_CHECKING_PATH}/weighing-booth-efficiency`;
export const ENVIRONMENT_CHECKING_STEPPER_PATH = `${ENVIRONMENT_CHECKING_PATH}/stepper`;
export const ENVIRONMENT_CHECKING_MATERIAL_PATH = `${ENVIRONMENT_CHECKING_PATH}/material-group`;
export const ENVIRONMENT_CHECKING_QUALITY_PATH = `${ENVIRONMENT_CHECKING_PATH}/quality-form-report`;
// route path for material identification
export const MATERIAL_IDENTIFICATION_PATH = '/material-identification';
export const MATERIAL_IDENTIFICATION_CREATE_PATH = `${MATERIAL_IDENTIFICATION_PATH}/create`;
export const MATERIAL_IDENTIFICATION_DETAIL_PATH = `${MATERIAL_IDENTIFICATION_PATH}/detail`;
// route path for other
export const MATERIAL_IDEN_PATH = '/material-identification';
export const INCIDENT_LIST_PATH = '/incident';
export const INCIDENT_DETIAL_PATH = '/incident-info';
export const INCIDENT_CREATE_PATH = '/incident-form';
export const AUDIT_PATH = '/audit-trail';
export const MASTER_PATH = '/master-setup';
export const SAMPLING_SUMMARY_PATH = '/sampling-summary';
export const IMAGE_GALLARY_PATH = '/imageGallery';
export const WEIGHING_PATH = '/weighing';
