const createData = (
  seqNo,
  inspectionLotOrigin,
  queue,
  itemCode,
  itemName,
  batchNo,
  storageLocation,
  bin,
  normalPlan,
  unit,
  deviationPlan,
  unit1,
  totalSampling,
  unit2,
  sampling,
  unit3,
  container,
  typeOfAnalytical,
  status,
  qauntity,
  counter,
  validStatus,
) => ({
  seqNo,
  inspectionLotOrigin,
  queue,
  itemCode,
  itemName,
  batchNo,
  storageLocation,
  bin,
  normalPlan,
  unit,
  deviationPlan,
  unit1,
  totalSampling,
  unit2,
  sampling,
  unit3,
  container,
  typeOfAnalytical,
  status,
  qauntity,
  counter,
  validStatus,
});

export const data = [
  createData(1, '09', '1', '10000001', 'Hydroxine Di Hydrochloride', 'M000000099', 'SB59', 0, 2, 'Drum', '2', 'Drum', '4', 'Drum', 30, 'G', 'AB:TH', 'CH', 'In Progress', '30T : 30B', 0, 'PASS'),
  createData(2, '01', '2', '10000007', 'Hydroxine Di Hydrochloride', 'M000000100', 'SB00', 'F1:01:13', 4, 'Drum', 0, 'Drum', '4', 'Drum', 50, 'G', 'PB:Spoon', 'MC:CH', 'Completed', '50T : 50B', 0, 'PASS'),
  createData(3, '01', '3', '10000004', 'Hydroxine Di Hydrochloride', 'M000000097', 'SB00', 'F1:01:13', 3, 'Drum', 1, 'Drum', '4', 'Drum', 100, 'ml', 'AB:TH', 'CH', 'Waiting', '100T : 1000B', 0, 'FAIL'),
];
