export const TABLE_ROW_DETAILS_SELECT = 'TABLE_ROW_DETAILS_SELECT';
export const ROW_DETAIL_DELETE = 'ROW_DETAIL_DELETE';
export const ROW_DETAIL_DELETING_REQUEST = 'ROW_DETAIL_DELETING_REQUEST';
export const ROW_DETAIL_SUCCESS_DELETE = 'ROW_DETAIL_SUCCESS_DELETE';
export const ROW_DETAIL_ERROR_DELETE = 'ROW_DETAIL_ERROR_DELETE';
export const TABLE_ROW_DETAILS_UNSELECT = 'TABLE_ROW_DETAILS_UNSELECT';
export const TABLE_PAGE_SET = 'TABLE_PAGE_SET';
export const TABLE_ROWS_PER_PAGE_SET = 'TABLE_ROWS_PER_PAGE_SET';
